# JSSP

### Imports

In [1836]:
# from dwave.system import DWaveSampler, EmbeddingComposite
# import dwave.inspector as inspector
import pandas as pd
import numpy as np
# import cvxpy as cp
import time
import dimod
import matplotlib.pyplot as plt
from matplotlib import rc
import gurobipy as gp
import math

### Annealing functions

In [1837]:
def sendToDwave(qubo, shots=100, beta_range=None):
    # Description: functions that solves a particular qubo problem

    # INPUT:
    # qubo: (matrix) representation of the xt*Q*x problem

    # OUTPUT:
    # sampleset: array of tuples of the form (solution, energy) of length "shots" containing posible (but not neccesarily feasible) solutions
    
    tic = time.perf_counter() # for time measuring
    sampleset = dimod.SimulatedAnnealingSampler().sample_qubo(qubo, num_reads=shots, beta_range=beta_range)
    sampleset = sampleset.aggregate() # solo agrega soluciones DIFERENTES.
    sampleset = [(sample, energy) for sample, energy in zip(sampleset.record.sample, sampleset.record.energy)]
    toc = time.perf_counter() # for time measuring
    print(f"Simulating {shots} instances of annealing took: {(toc-tic)}s")
    # print("Sampleset sin filtrar: ", sampleset)
    return sampleset

def from_sample_to_int(sample):
    binary_list = sample[0].tolist()

    # Convert the binary list to a string and join the elements
    binary_string = ''.join(str(x) for x in binary_list)
    # Use the int() function with base 2 to convert the binary string to an integer
    result = int(binary_string, 2)
    return result

def count_elements(sample_list, total_spaces):
    frequency_dict = {}
    energy_dict = {}
    for item in sample_list:
        hashable_item = from_sample_to_int(item)
        if hashable_item in frequency_dict:
            frequency_dict[hashable_item] += 1
        else:
            energy_dict[hashable_item] = int(item[1])
            frequency_dict[hashable_item] = 1
    results_list = [bin(item)[2:] for item in frequency_dict]
    energies = list(energy_dict.values())
    frequencies = list(frequency_dict.values())

    new_results = []
    for result in results_list:
        if len(result) != total_spaces:
            ceros_string = '0' * int(total_spaces - len(result))
            result = ceros_string + result
        new_results.append(result)
    result = {'results': new_results, 'energies': energies, 'frequencies': frequencies}
    return result

def make_histogram(samples_dict):
    # Constructing an histogram to represent the solutions

    df = pd.DataFrame(samples_dict)
    print(df)

    # Sample data
    data = samples_dict

    # Extract the labels and the amounts into separate lists
    labels = data['results']
    amounts = data['frequencies']
    energies = data['energies']

    # Create a bar plot
    plt.bar(labels, amounts)

    for i, count in enumerate(amounts):
        plt.text(i, count, str(count), ha='center', va='bottom')

    # Add labels and title to the plot
    plt.xlabel('Soluciones')
    plt.ylabel('Cantidades')
    plt.title('Soluciones y cantidad de veces que aparecen')

    # Show the plot
    plt.show()


In [1838]:
def lowest_energy(sampleset):  # Finds the lowest energy solution
    
    # Description: given a full sampleset (tuples of the form (solution, energy) finds the lowest energy SAMPLE.
    # INPUTS:
    # Sampleset: a sampleset of the form list((solution, energy))

    # OUTPUTS:
    # best: a tuple of the form (solution, energy)

    if len(sampleset):
        energies = np.array([el[1] for el in sampleset])  # energias
        index = np.argmin(energies)  # indice de la de menor energia
        ret = sampleset[index]  # solucion de menor energia
        return ret

    else:
        return None

In [1839]:
# def sendToDwaveSampler(qubo, shots=100):
#     sampler = DWaveSampler(solver={'topology__type':'pegasus'})
#     embedding = EmbeddingComposite(sampler)
#     sampleset = embedding.sample_qubo(qubo, num_reads=shots)
#     # inspector.show(running)
#     # print(running)
#     return sampleset

### Auxiliary functions

In [1840]:
def get_index(v_list, value):
    index = 0
    for l in v_list:
        if l == value:
            return index
        index += 1
    return None


In [1841]:
def get_subindexes(item):
    index_list = ""
    for sub_item in item:
        if index_list == "":
            index_list += str(sub_item)
        else:
            index_list += ","
            index_list += str(sub_item)
    return index_list

In [1842]:
def get_variable_index(x, var_name):
    try:
        arr = x.index(var_name)
        return arr
    except:
        return None

In [1843]:
def add_Q_value(x, q_list, i, j, value):
    index_i = get_variable_index(x, i)
    index_j = get_variable_index(x, j)
    
    if index_i is not None and index_j is not None:
        q_list.append([index_i, index_j, value])


In [1844]:

# list1 = []
# x = ["v1", "v2"]
# add_Q_value(x, list1, "v2", "v2", -10)


In [1845]:
def update_Q(Q, newQ, p = 1):
    for q in newQ:
        if q[0] == q[1]:
            Q[q[0]][q[0]] += p * q[2]
        else:
            Q[q[0]][q[1]] += p * q[2]
            Q[q[1]][q[0]] += p * q[2]



In [1846]:
def get_Q_value(Q, x, i, j):
    index_i = get_variable_index(x, i)
    index_j = get_variable_index(x, j)
    if index_i is not None and index_j is not None:
        return Q[index_i][index_j]
    
    

In [1847]:
def print_Q_item(Q, x, i, j):
    # i, j numeric indexes
    if i>=0 and i<len(x) and j>=0 and j<len(x):
        var_i = x[i]
        var_j = x[j]
        print("{", var_i, ",", var_j, "} =", Q[i][j])

In [1848]:
def print_Q_nonZero(Q, x):
    for i in range(len(Q)):
        for j in range(len(Q[i])):
            if Q[i][j] != 0:
                print_Q_item(Q, x, i, j)


In [1849]:
a = np.matrix([1,2,4,8])


a = np.zeros((1,2))
a[0][1] = 3
q = a.transpose()*a

In [1850]:
def linear_constraint(x, vars, a, b=0):

    Q_list = []
    if len(vars) != len(a):
        print("Linear constraint variables error!!!!")
        return Q_list

    a_vector = np.array(a)
    matrix = np.outer(a_vector, a_vector) - 2*b*np.diag(a_vector)

    # print(np.outer(a_vector, a_vector))
    # print(- 2*b*np.diag(a_vector))

    # print(matrix)
    
    for i in range(len(matrix)):
        for j in range(i, len(matrix[i])):
            add_Q_value(x, Q_list, vars[i], vars[j], matrix[i][j])
    
    return Q_list


In [1851]:
def print_all_variables(bitvector, x, S_q, L_q, E_q, slack,X, qb_amount):
    i = 0
    print(len(x))
    while i < len(x):
        if isinstance(x[i], S_q):
            bits = [bitvector[i+j] for j in range(qb_amount)]
            var = x[i].s
            i+=qb_amount
        elif isinstance(x[i], L_q):
            bits = [bitvector[i+j] for j in range(qb_amount)]
            var = x[i].l
            i+=qb_amount
        elif isinstance(x[i], E_q):
            bits = [bitvector[i+j] for j in range(qb_amount)]
            var = x[i].e
            i+=qb_amount
        elif isinstance(x[i], slack):
            slacks = [s for s in x if x[i].same(s)]
            bits = [bitvector[x.index(s)] for s in slacks]
            var = x[i].full_slack_string()
            i+=len(slacks)
        elif isinstance(x[i], X):
            Xs = [s for s in x if x[i].same(s)]
            bits = np.array([bitvector[x.index(s)] for s in Xs])
            n = int(np.sqrt(len(Xs)))
            bits = bits.reshape((n,n)).transpose()
            var = x[i].matrix_name()
            print(f"{var} =")
            print(bits.astype(int))
            i+=len(Xs)
            continue
        else:
            print(f"{x[i]} = {bitvector[i]}")
            i+=1
            continue
        print(f"{var} = {np.inner(bits, 2**np.arange(len(bits)))}")

## (1) Constants and Definitions



### 1.1) Time slots

T_slots = {1,2,3,... 16} (4 bits: 4qb)

In [1852]:
qb_amount = 4

### 1.2) Products
P = {B1, B2, LAM1, LAM2}
              = {0,   1,    2,    3}

In [1853]:
class Product:
    def __init__(self, name:str) -> None:
        self.name = name
    
    def __str__(self) -> str:
        return self.name
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.name == __value.name

P = [Product("B1"), Product("B2"), Product("LAM1"), Product("LAM2")]

### 1.3) Jobs
J = {JB1, JB2}

In [1854]:
class Job:
    def __init__(self, name:str, final_product: Product = None, amount: int=None, deadline: int=None) -> None:
        self.name = name
        self.final_product = final_product
        self.final_operations = []
        self.amount = amount
        self.deadline = deadline

    def __str__(self) -> str:
        return self.name
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.name == __value.name


J = [Job("JB1"), Job("JB2")]



### 1.4) successors:
      LAM1 -> B1 ---- P2 -> P0
      LAM2 -> B1 ----   P3 -> P0
      LAM1 -> B2 ----   P2 -> P1

In [1855]:
successors = [[P[2], P[0]], [P[3], P[0]], [P[2], P[1]]]

### 1.5) amounts:
      a_JB1 = 4
      a_JB2 = 2

In [1856]:
J[0].amount = 4
J[1].amount = 2

### 1.6) final product of job:
      JB1 : B1
      JB2 : B2

In [1857]:
for j in J:
    j.final_product = P[J.index(j)]


### 1.7) deadline:
      D_JB1 = 10
      D_JB2 = 11

In [1858]:
J[0].deadline = 10
J[1].deadline = 11

### 1.8) Machines
M = {M1, M2, M3}

In [1859]:
class Machine:
    def __init__(self, name:str) -> None:
        self.name = name
    
    def __str__(self) -> str:
        return self.name
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.name == __value.name

M = [Machine("M1"), Machine("M2"), Machine("M3")]

#### 1.8.1) speeds = 1 for each machine

#### 1.8.2) production machines:

        LAM1, LAM2 -> M1
        B1, B2 -> M2
        B1 -> M3

### 1.9) Operations

      {O_jpms : j=job, i=product, m=machine, s=splitting}

      O_(JB1,LAM1,M1,1)     ->   O_(J0,P2,M0,1) -> O[0]
      O_(JB1,LAM1,M1,2)     ->   O_(J0,P2,M0,2) -> O[1]
      O_(JB1,LAM2,M1,1)     ->   O_(J0,P3,M0,1) -> O[2]
      O_(JB1,LAM2,M1,2)     ->   O_(J0,P3,M0,2) -> O[3]
      O_(JB1,B1,M2,1)       ->   O_(J0,P0,M1,1) -> O[4]
      O_(JB1,B1,M3,1)       ->   O_(J0,P0,M2,1) -> O[5]
      O_(JB2,LAM1,M1,1)     ->   O_(J1,P2,M0,1) -> O[6]
      O_(JB2,B2,M2,1)       ->   O_(J1,P1,M1,1) -> O[7]

In [1860]:
class Operation:
    def __init__(self, job: Job, product: Product, machine: Machine, splitting: int=None) -> None:
        self.job = job
        self.product = product
        self.machine = machine
        self.splitting = splitting

    def __str__(self) -> str:
        if self.splitting is not None:
            return f"{self.job},{self.product},{self.machine},{self.splitting}"
        else:
            return f"{self.job},{self.product},{self.machine}"
        
    def to_x_index(self) -> str:
        if self.splitting is not None:
            return f"{self.job},{self.product},{self.splitting}"
        else:
            return f"{self.job},{self.product}"
        
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.job == __value.job and self.product == __value.product and \
            self.machine == __value.machine and (self.splitting is None or self.splitting == __value.splitting)

In [1861]:
O = [ Operation(J[0], P[2], M[0], 1),
     Operation(J[0], P[2], M[0], 2), 
     Operation(J[0], P[3], M[0], 1),
     Operation(J[0], P[3], M[0], 2),
     Operation(J[0], P[0], M[1]),      #omit splitting when not needed
     Operation(J[0], P[0], M[2]),
     Operation(J[1], P[2], M[0]),
     Operation(J[1], P[1], M[1])
     ]

In [1862]:
# final operations by job

for o in O:
    for j in J:
        if o.job == j and o.product == j.final_product:
            j.final_operations.append(o)


### 1.10) Operations by Machine m:

        OM_m' = {O_jpms : m=m'}
        o_m = #(OM_m)

      M1: {
            O_(JB1,LAM1,M1,1);
            O_(JB1,LAM1,M1,2)
            O_(JB1,LAM2,M1,1)
            O_(JB1,LAM2,M1,2)
            O_(JB2,LAM1,M1,1)
      }
      o_M1 = 5

      M2: {
          O_(JB1,B1,M2,1);
          O_(JB2,B2,M2,1)
      }
      o_M2 = 2

      M3: { O_(JB1,B1,M3,1) }
      o_M3 = 1


In [1863]:
OM = []
for m in M:
     count = 0
     op_list = []
     for o in O:
          if o.machine == m:
               op_list.append(o)
     OM.append(op_list)



1.11) (jps), [jpms] : lexicographic order

### 1.12) Transition Cost : TC^m_(i,i')

In [1864]:
TC1 = [
     [0,       1500,	0,	1500,	0],
     [200,	0,	     200,	0,	     200],
     [0,	     1500,	0,	1500,	0],
     [200,	0,	     200, 0,	     200],
     [0,	     1500,	0,	1500,	0]
]
TC2 = [
     [0, 200],
     [200, 0]
]
TC3 = [[0]]

TC = [TC1, TC2, TC3]

### 1.13) Transition Time : TT^m_(p,p')

In [1865]:
TT1 = [
     [0,	1,	0,	1,	0],
     [0,	0,	0,	0,	0],
     [0,	1,	0,	1,	0],
     [0,	0,	0,	0,	0],
     [0,	1,	0,	1,	0]
]
TT2 = [
     [0, 1],
     [2, 0]
]
TT3 = [[0]]

TT = [TT1, TT2, TT3]

### 1.14) Realizations

      A_JB1,1     = {O_(JB1,LAM1,M1,1); O_(JB1,LAM2,M1,1); O_(JB1,B1,M2,1)}
                  = [O[0], O[2], O[4]]
      A_JB1,2 = {O_(JB1,LAM1,M1,2); O_(JB1,LAM2,M1,2); O_(JB1,B1,M3,1)}
                  = [O[1], O[3], O[5]]
      A_JB2,1 = {O_(JB2,LAM1,M1,1); O_(JB2,B2,M2,1)}
                  = [O[6], O[7]]

      O_(JB1,LAM1,M1,1)     ~   O_(J0,P2,M0,1) ~ O[0]
      O_(JB1,LAM1,M1,2)     ~   O_(J0,P2,M0,2) ~ O[1]
      O_(JB1,LAM2,M1,1)     ~   O_(J0,P3,M0,1) ~ O[2]
      O_(JB1,LAM2,M1,2)     ~   O_(J0,P3,M0,2) ~ O[3]
      O_(JB1,B1,M2,1)       ~   O_(J0,P0,M1,1) ~ O[4]
      O_(JB1,B1,M3,1)       ~   O_(J0,P0,M2,1) ~ O[5]
      O_(JB2,LAM1,M1,1)     ~   O_(J1,P2,M0,1) ~ O[6]
      O_(JB2,B2,M2,1)       ~   O_(J1,P1,M1,1) ~ O[7]


In [1866]:
A = [
     [O[0], O[2], O[4]],
     [O[1], O[3], O[5]],
     [O[6], O[7]]
]

1.14.1) Precedences (operations)

      A_JB1,1:
          O_(JB1,LAM1,M1,1) -> O_(JB1,B1,M2,1)
          O_(JB1,LAM2,M1,1) -> O_(JB1,B1,M2,1)
      A_JB1,2:
          O_(JB1,LAM1,M1,2) -> O_(JB1,B1,M3,1)
          O_(JB1,LAM2,M1,2) -> O_(JB1,B1,M3,1)
      A_JB2,1:
          O_(JB2,LAM1,M1,1) -> O_(JB2,B2,M2,1)

In [1867]:
prec = [
          [O[0], O[4]],
          [O[2], O[4]],
          [O[1], O[5]],
          [O[3], O[5]],
          [O[6], O[7]],
]

### 1.15) Costs K

1.15.1) K1 = 500 (K0) for both jobs

1.15.2) K2 = 100 (K1) for both jobs

1.15.3) K3 = 1200 (K2) for all machines

1.15.4) K4 = 50 (K3) for all machines

In [1868]:
K1 = 500
K2 = 100
K3 = 1200
K4 = 50

In [1869]:
index_of_JB1 = get_index(J,"JB2") # ejemplo para obtener el indice de una variable
print(index_of_JB1)

None


## (2) Variables

### Variable Classes

In [1870]:
#Start Time
class S:
    def __init__(self, operation: Operation)->None:
        self.operation = operation

    def __str__(self) -> str:
        return f"S{{{self.operation}}}"
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.operation == __value.operation
    
#Start Time qbits
class S_q:
    def __init__(self, s:S, qbit: int) -> None:
        self.s = s
        self.qbit = qbit
    
    def __str__(self) -> str:
        return f"{self.s}_{self.qbit}"

    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.s == __value.s and self.qbit == __value.qbit
    
#Time Interval
class L:
    def __init__(self, operation:Operation)->None:
        self.operation = operation

    def __str__(self) -> str:
        return f"L{{{self.operation}}}"
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.operation == __value.operation
    
#Time Interval qbits
class L_q:
    def __init__(self, l:L, qbit: int) -> None:
        self.l = l
        self.qbit = qbit
    
    def __str__(self) -> str:
        return f"{self.l}_{self.qbit}"

    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.l == __value.l and self.qbit == __value.qbit
    
#Job Finish Time
class E:
    def __init__(self, job: Job) -> None:
        self.job = job
    
    def __str__(self) -> str:
        return f"E{{{self.job}}}"

    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.job == __value.job
    
#Job Finish Time qbits
class E_q:
    def __init__(self, e:E, qbit: int) -> None:
        self.e = e
        self.qbit = qbit
    
    def __str__(self) -> str:
        return f"{self.e}_{self.qbit}"

    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.e == __value.e and self.qbit == __value.qbit

#on time
class d:
    def __init__(self, job: Job) -> None:
        self.job = job

    def __str__(self) -> str:
        return f"d{{{self.job}}}"

    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.job == __value.job
    

#Operation Not Done
class bz:
    def __init__(self, l:L)->None:
        self.l = l

    def __str__(self) -> str:
        return f"bz{{{self.l}}}"
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.l == __value.l

#X Matrix Elements
class X:
    def __init__(self, operation:Operation, k: int)->None:
        self.operation = operation
        self.k = k

    def __str__(self) -> str:
        return f"X^{self.operation.machine}({{{self.operation.to_x_index()}}}, {self.k})"
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.operation == __value.operation and self.k == __value.k
    
    def same(self, __value: object) -> bool:
        return type(__value) == type(self) and self.operation.machine == __value.operation.machine
    
    def matrix_name(self) -> str:
        return f"X^{self.operation.machine}"
    
#Null column indicator on X^m
class u:
    def __init__(self, machine: Machine, k : int) -> None:
        self.machine = machine
        self.k = k
    
    def __str__(self) -> str:
        return f"u_{{{','.join((str(self.machine), str(self.k)))}}}"

    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.machine == __value.machine and self.k == __value.k
    
#Auxiliary variable for quadratic interactions between X and L o S (name: y if S, z if L)
class AuxQuadXLS:
    def __init__(self,operation:Operation, k: int, qbit:int, name:str)->None:
        self.operation = operation
        self.k = k
        self.qbit = qbit
        self.name = name

    def __str__(self) -> str:
        return f"{self.name}^{self.operation.machine}({{{self.operation.to_x_index()}}}, {self.k})_{self.qbit}"
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.operation == __value.operation and self.k == __value.k\
            and self.name ==__value.name and self.qbit == __value.qbit
    
#Auxiliary variable for quadratic interactions between X'S
class AuxQuadXs:
    def __init__(self, operation1:Operation, operation2:Operation, k:int)->None:
        self.operation1 = operation1
        self.operation2 = operation2
        self.k = k

    def __str__(self) -> str:
        return f"w^{self.operation1.machine}({','.join((self.operation1.to_x_index(), self.operation2.to_x_index(), str(self.k)))})"
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.operation1 == __value.operation1 and \
            self.operation2 == __value.operation2
    
class slack:
    def __init__(self, constraint: str, id: any, qbit:int) -> None:
        self.constraint = constraint
        self.id = id
        self.qbit = qbit

    def __str__(self) -> str:
        return f"slack_{self.constraint}_{self.id}_{self.qbit}"
    
    def __eq__(self, __value: object) -> bool:
        return type(__value) == type(self) and self.constraint == __value.constraint \
            and self.id == __value.id and self.qbit == __value.qbit
    
    def same(self, __value: object) -> bool:
        return type(__value) == type(self) and self.constraint == __value.constraint \
            and self.id == __value.id

    def full_slack_string(self) -> str:
        return f"slack_{self.constraint}_{self.id}"

In [1871]:
x = []  # all variables vector

### 2.1) Start Time: S_jpms (4qb)

In [1872]:
S_list = []
for o in O:
    S_list.append(S(o))

2.1.1) qubit digits:

    {S_jpms}_q (binary variable) for each q = 0,1,2,3
    S_jpms = sum_q ( 2^q * {S_jpms}_q )

In [1873]:
S_q_list = []
for s in S_list:
    for q in range(qb_amount):
        S_q_list.append(S_q(s,q))

x.extend(S_q_list)

### 2.2) Time Interval: L_jpms (4qb)

In [1874]:
L_list = []
for o in O:
    L_list.append(L(o))

2.2.1) qubit digits:

    {L_jpms}_q (binary variable) for each q = 0,1,2,3
    L_jpms = sum_q ( 2^q * {L_jpms}_q )

In [1875]:
L_q_list = []
for l in L_list:
    for q in range(qb_amount):
        L_q_list.append(L_q(l, q))

x.extend(L_q_list)

### 2.3) Job finish time / Dummy operation start time:

    E_j (4qb)

In [1876]:
E_list = []
for j in J:
    E_list.append(E(j))

2.3.1) qubit digits:

    {E_j}_q (binary variable) for each q = 0,1,2,3
      E_JB1 = sum_q ( 2^q * {E_JB1}_q )
      E_JB2 = S_(JB2,B2,M2,1) + L_(JB2,B2,M2,1)   ((((DEFINED BY OTHER VARIABLES))))


In [1877]:
E_q_list = []
for e in E_list:
    for q in range(qb_amount):
        E_q_list.append(E_q(e,q))

x.extend(E_q_list)

### 2.4) Job excess time:

      delta_j^max = E_j - D_j    ((((Not needed, replaceable by E_j -  D_j ))))

### 2.5) "On time" binary variable:

      d_j = ( E_j <= D_j )

In [1878]:
d_list = []
for j in J:
    d_list.append(d(j))

x.extend(d_list)

### 2.6) Operation not done / discarded / null operation:

      bz_jpms = ("O_jpms discarded") = (L_jpms == 0)

In [1879]:
bz_list = []
for l in L_list:
    bz_list.append(bz(l))
    
x.extend(bz_list)

### 2.7) Null operations amount in machine m:

      ntz_m = sum_jps( bz_jpms )      (((always replaceable by the sum)))

### 2.8) The X matrix: X^m, for each machine m

      X^m_(jpms, k) = ("O_jpms is done in k-th place in machine m")
      X^M1, 5x5       
      X^M2, 2x2
      X^M3, 1x1
      (((( X^m_(jpms, k) = 0 if k > o_m - ntz_m ))))

In [1880]:
X_list = []

for m in M:
    for k in range(len(OM[M.index(m)])):
        for o in OM[M.index(m)]:
            X_list.append(X(o, k+1))


x.extend(X_list)

### 2.9) Null column indicator in X^m matrix

      u_mk = ( k <= o_m - ntz_m)

In [1881]:
u_list = []
m_index = 0
for m in M:
    for k in range(len(OM[m_index])):
        u_list.append(u(m, k+1))
    m_index += 1

x.extend(u_list)

### 2.10) Auxiliary variables for quadratic constraints

(*) i and j represents a set of indexes (j,p,m,s) of an operation

#### 2.10.1) X and S

$$ y^m_{jps,k,q} = X^m_{jps,k} * {S_{jpms}}_q $$

for all k = 1,2,..., o_m


In [1882]:
y_list = []
# x=[]
for m in M:
    op_list = OM[M.index(m)]
    for o in op_list:
        if len(op_list) <= 1:
            continue
        for k in range(1, len(op_list) + 1):
            for q in range(qb_amount):
                y_list.append(AuxQuadXLS(o, k, q, "y"))

# x.extend(y_list)
print(len(y_list))
# print([str(y) for y in y_list])

116



#### 2.10.2) X and L

$$ z^m_{jps,k,q} = X^m_{jps,k} * {L_{jpms}}_q $$

for all k = 1,2,...,o_m-1

In [1883]:
z_list = []
# x = []
for m in M:
    op_list = OM[M.index(m)]
    for o in op_list:
        if len(op_list) <= 1:
            continue
        for k in range(1, len(op_list)):
            for q in range(qb_amount):
                z_list.append(AuxQuadXLS(o, k, q, "z"))

# x.extend(z_list)
print(len(z_list))

88


#### 2.10.3) X and X

$$ w^m_{jps,j'p's',k} = X^m_{jps,k-1} * X^m_{j'p's',k} $$

for all k = 2,3,...,o_m

In [1884]:
w_list = []
# x = []
for m in M:
    op_list = OM[M.index(m)]
    for o1 in op_list:
        for o2 in op_list:
            if len(op_list)>1 and o1 != o2:
                for k in range(2, len(op_list) + 1):
                    w_list.append(AuxQuadXs(o1, o2, k))

# x.extend(w_list)
print(len(w_list))
print([str(w) for w in w_list])


82
['w^M1(JB1,LAM1,1,JB1,LAM1,2,2)', 'w^M1(JB1,LAM1,1,JB1,LAM1,2,3)', 'w^M1(JB1,LAM1,1,JB1,LAM1,2,4)', 'w^M1(JB1,LAM1,1,JB1,LAM1,2,5)', 'w^M1(JB1,LAM1,1,JB1,LAM2,1,2)', 'w^M1(JB1,LAM1,1,JB1,LAM2,1,3)', 'w^M1(JB1,LAM1,1,JB1,LAM2,1,4)', 'w^M1(JB1,LAM1,1,JB1,LAM2,1,5)', 'w^M1(JB1,LAM1,1,JB1,LAM2,2,2)', 'w^M1(JB1,LAM1,1,JB1,LAM2,2,3)', 'w^M1(JB1,LAM1,1,JB1,LAM2,2,4)', 'w^M1(JB1,LAM1,1,JB1,LAM2,2,5)', 'w^M1(JB1,LAM1,1,JB2,LAM1,2)', 'w^M1(JB1,LAM1,1,JB2,LAM1,3)', 'w^M1(JB1,LAM1,1,JB2,LAM1,4)', 'w^M1(JB1,LAM1,1,JB2,LAM1,5)', 'w^M1(JB1,LAM1,2,JB1,LAM1,1,2)', 'w^M1(JB1,LAM1,2,JB1,LAM1,1,3)', 'w^M1(JB1,LAM1,2,JB1,LAM1,1,4)', 'w^M1(JB1,LAM1,2,JB1,LAM1,1,5)', 'w^M1(JB1,LAM1,2,JB1,LAM2,1,2)', 'w^M1(JB1,LAM1,2,JB1,LAM2,1,3)', 'w^M1(JB1,LAM1,2,JB1,LAM2,1,4)', 'w^M1(JB1,LAM1,2,JB1,LAM2,1,5)', 'w^M1(JB1,LAM1,2,JB1,LAM2,2,2)', 'w^M1(JB1,LAM1,2,JB1,LAM2,2,3)', 'w^M1(JB1,LAM1,2,JB1,LAM2,2,4)', 'w^M1(JB1,LAM1,2,JB1,LAM2,2,5)', 'w^M1(JB1,LAM1,2,JB2,LAM1,2)', 'w^M1(JB1,LAM1,2,JB2,LAM1,3)', 'w^M1(JB1,LAM1,2,J


### 2.11) Slack variables

In [1885]:
for p in prec:
    for q in range(qb_amount):
        x.append(slack("1", p[0], q))

for j in J:
    for of in j.final_operations:
        for q in range(qb_amount):
            x.append(slack("1_2", of, q))

for l_q in L_q_list:
    x.append(slack("2", l_q.l, l_q.qbit))

for e in E_list:
    for q in range(qb_amount):
        x.append(slack("3", e, q))

for u_mk in u_list:
    m_op_list = OM[M.index(u_mk.machine)]
    n = math.ceil(math.log2(max(u_mk.k, len(m_op_list) - u_mk.k + 1)))
    for q in range(n):
        x.append(slack("6", u_mk, q))

for p in prec:
    for q in range(qb_amount):
        x.append(slack("7_1", p[0], q))

for j in J:
    for of in j.final_operations:
        for q in range(qb_amount):
            x.append(slack("7_1_1", of, q))

# for m in M:
#     for k in range(2, len(OM[M.index(m)]) + 1):
#         for q in range(6):
#             x.append(slack("8", u(m, k), q))


In [1886]:
print([str(u) for u in u_list])

['u_{M1,1}', 'u_{M1,2}', 'u_{M1,3}', 'u_{M1,4}', 'u_{M1,5}', 'u_{M2,1}', 'u_{M2,2}', 'u_{M3,1}']


In [1887]:


print([str(k) for k in x])
print(len(x))


['S{JB1,LAM1,M1,1}_0', 'S{JB1,LAM1,M1,1}_1', 'S{JB1,LAM1,M1,1}_2', 'S{JB1,LAM1,M1,1}_3', 'S{JB1,LAM1,M1,2}_0', 'S{JB1,LAM1,M1,2}_1', 'S{JB1,LAM1,M1,2}_2', 'S{JB1,LAM1,M1,2}_3', 'S{JB1,LAM2,M1,1}_0', 'S{JB1,LAM2,M1,1}_1', 'S{JB1,LAM2,M1,1}_2', 'S{JB1,LAM2,M1,1}_3', 'S{JB1,LAM2,M1,2}_0', 'S{JB1,LAM2,M1,2}_1', 'S{JB1,LAM2,M1,2}_2', 'S{JB1,LAM2,M1,2}_3', 'S{JB1,B1,M2}_0', 'S{JB1,B1,M2}_1', 'S{JB1,B1,M2}_2', 'S{JB1,B1,M2}_3', 'S{JB1,B1,M3}_0', 'S{JB1,B1,M3}_1', 'S{JB1,B1,M3}_2', 'S{JB1,B1,M3}_3', 'S{JB2,LAM1,M1}_0', 'S{JB2,LAM1,M1}_1', 'S{JB2,LAM1,M1}_2', 'S{JB2,LAM1,M1}_3', 'S{JB2,B2,M2}_0', 'S{JB2,B2,M2}_1', 'S{JB2,B2,M2}_2', 'S{JB2,B2,M2}_3', 'L{JB1,LAM1,M1,1}_0', 'L{JB1,LAM1,M1,1}_1', 'L{JB1,LAM1,M1,1}_2', 'L{JB1,LAM1,M1,1}_3', 'L{JB1,LAM1,M1,2}_0', 'L{JB1,LAM1,M1,2}_1', 'L{JB1,LAM1,M1,2}_2', 'L{JB1,LAM1,M1,2}_3', 'L{JB1,LAM2,M1,1}_0', 'L{JB1,LAM2,M1,1}_1', 'L{JB1,LAM2,M1,1}_2', 'L{JB1,LAM2,M1,1}_3', 'L{JB1,LAM2,M1,2}_0', 'L{JB1,LAM2,M1,2}_1', 'L{JB1,LAM2,M1,2}_2', 'L{JB1,LAM2,M1,2}_3',

## (3) Cost: Objective Function (OF)

minimize 3.1) + 3.2) + 3.3) = 

        sum_jpms( (1 - bz_jpms)*(K3_m + K4_m*L_jpms) ) +
        sum_mk,jps,j'i's' ( X^m_jps,k-1 * TC^m_i,i' * X^m_j'i's',k ) +
        sum_j( (1 - d_j) * ( K1_j + K2_j*(E_j - D_j) ) )

In [1888]:
#initializar matriz Q
Q = np.zeros((len(x), len(x)))

In [1889]:
C = 0 # global xtQx constant


<h3>3.1) production cost</h3>


In [1890]:
Q_FO1 = [] # lista de indices y valor a sumar, ejemplo: [[1,2,16], [1,1,31], [4,3,-10]]
# para cada valor nuevo de Q para la dupla de variables i,j se agrega a la lista de Q_FO1 con add_Q_value(x, q_list, i, j, value)

$$\sum_{jpms}( (1 - bz_{jpms})*(K3_m + K4_m*\sum_{q}(2^q*{L_{jpms}}_q)) ) = $$

  sum_jpms {

      K3_m                   //constant, NOT CONSIDERED IN THE OF

    }


In [1891]:
C_FO1 = K3*len(O)   # constant of FO1
print(C_FO1)

9600



  \+ sum_jpms {

      - K3_m * bz_jpms

    }
    
      -> Q_{bz_jpms, bz_jpms} = - K3_m         for all operation jpms

In [1892]:
for var in bz_list:
    add_Q_value(x, Q_FO1, var, var, -K3)

\+ sum_jpmsq {
  
    K4_m * 2^q * {L_jpms}_q

  }
  
    -> Q_{L_jpms_q, L_jpms_q} = K4_m * 2^q         for all operation jpms, and bit q


In [1893]:
# for lq in L_q:
#     add_Q_value(x, Q_FO1, lq, lq, K4 * 2 ** (int(lq[-1])))

for l in L_list:
    for q in range(qb_amount):
        lq = L_q(l, q)
        add_Q_value(x, Q_FO1, lq, lq, K4 * 2**q)

\+ sum_jpmsq {

    - K4_m * bz_jpms * 2^q * {L_jpms}_q

  }
  
    -> Q_{bz_jpms, L_jpms_q} = -1/2 * K4_m * 2^q         for all operation jpms, and bit q


In [1894]:

for i in range(len(O)):
    var = bz_list[i]
    l = L_list[i]
    for q in range(qb_amount):
        add_Q_value(x, Q_FO1, var, L_q(l,q) , -(1/2) * K4 * 2**q)

# print(Q_FO1)
update_Q(Q, Q_FO1)
C += C_FO1
print(C_FO1)

9600


<h3>3.2) transition cost</h3>

$$\sum_{mk,jps,j'i's'} ( X^{m}_{jps,k-1} * TC^{m}_{i,i'} * X^{m}_{j'i's',k} ) = $$

    sum_m {
      sum_k {
        sum_i,i' {
          TC^m_i,i' * sum_(js)(j's') {
            X^m_(jps, k - 1) * X^m_(j'i's', k)   //quadratic (X^2)
          }
        }
      }
    }

    -> Q_{X^m_(jps, k - 1), X^m_(j'i's', k)} = 1/2 * TC^m_i,i'  
    
         for all m=1,2,3; column k; i,i'=1,2,...8; j,j'=1,2; s,s'=1,2
         
      ~ add_Q_value(x, Q_FO2, X^m_(jps, k-1)), X^m_(j'i's', k), 1/2 * TC^m_i,i')

In [1895]:

Q_FO2 = []

m_index = 0
for m in M:
    if len(OM[m_index])>1:
        for k in range(len(OM[m_index])):
            for o1 in OM[m_index]:
                for o2 in OM[m_index]:
                    new_value = (1/2) * TC[m_index] [get_index(P,o1.product)] [get_index(P,o2.product)]
                    if o1 != o2 and new_value != 0:
                        add_Q_value(x,Q_FO2,
                                    X(o1,k),
                                    X(o2,k+1),
                                    new_value)
    m_index += 1
            
update_Q(Q, Q_FO2)

<h3>3.3) out of time cost</h3>

In [1896]:
Q_FO3 = []

  $$\sum_{j}( (1 - d_j) * ( K1_j + K2_j*(E_j - D_j) ) ) =$$

    sum_j {
      K1^j - K2^j * D_j       //constant, NOT CONSIDERED IN THE OF
    }


In [1897]:
C_FO3 = 0    

for j in J:
    C_FO3 += K1 - K2*j.deadline     # constant of FO3

print(C_FO3)

-1100



  \+ sum_j {

    - ( K1^j - K2^j * D_j ) * d_j   //linear (d_j)

  }
  
      -> Q_{d_j} = K2^j * D_j - K1^j   for all j=1,2



In [1898]:
for d_j in d_list:
    job = d_j.job
    new_value = K2 * job.deadline - K1
    add_Q_value(x, Q_FO3, d_j, d_j, new_value)

\+ sum_jq {

    2^q * K2^j * {E_j}_q   //linear (digits of E_j)

  }
  
      -> Q_{E_j_q} = 2^q * K2^j   for all j=1,2; q=0,1,2,3

In [1899]:
for e in E_list:
    for q in range(qb_amount):
        new_value = (2**q) * K2
        e_q = E_q(e,q)
        add_Q_value(x, Q_FO3, e_q, e_q, new_value)

\+ sum_jq {

    - 2^q * K2^j * d_j * {E_j}_q    //quadratic (d*E)
    
  }

      -> Q_{d_j, E_j_q} = -1/2 * 2^q * K2^j   for all j=1,2; q=0,1,2,3

In [1900]:
for e in E_list:
    d_j = d_list[E_list.index(e)]
    for q in range(qb_amount):
        new_value = -(1/2) * (2**q) * K2
        add_Q_value(x, Q_FO3, d_j, E_q(e,q), new_value)
        # print(Q_FO3)

update_Q(Q, Q_FO3)
C += C_FO3
print(C_FO3)

print(get_variable_index(x, bz_list[0]))

# print_Q_nonZero(Q, x)


-1100
74


In [1901]:
Q_FO = Q.copy()

In [1902]:
C_FO = C
print(C_FO) # constant of FO

8500


In [1903]:
# sampleset = sendToDwave(Q, 10)
# samples_dict = count_elements(sampleset, len(Q))
# make_histogram(samples_dict)



In [1904]:
# for i in x:
#     print(f"{i} = {lowest_energy(sampleset)[0][x.index(i)]}")

In [1905]:
# vector=[]
# for i in x:
#     vector.append(1 if (isinstance(i, bz) or isinstance(i, d) or isinstance(i, E_q)) else 0)
# print(vector)
# print(np.sum(vector))
# vector = np.array(vector)
# print(vector.T@Q@vector)
# vector = np.array(lowest_energy(sampleset)[0])
# print(vector.T@Q@vector)

## (4) Constraints



### 4.1) Products demands

#### 4.1.1) Precedent operations

$$ L_{jpms} \geq \sum_{s'} { L_{jp'm's'}} $$
for all precedent operations O_{jp'm'}
    
    (*) speed = 1 always
    (*) alpha = 1 always (precedent product requirements)

    L_(JB1,B1,M2,1) >= L_(JB1,LAM1,M1,1)
    L_(JB1,B1,M2,1) >= L_(JB1,LAM2,M1,1)

    L_(JB1,B1,M3,1) >= L_(JB1,LAM1,M1,2)
    L_(JB1,B1,M3,1) >= L_(JB1,LAM2,M1,2)

    L_(JB2,B2,M2,1) >= L_(JB2,LAM1,M1,1)


In [1906]:
# Q = np.zeros((len(x), len(x)))
# P( L - L' - slack)^2
Q_C1 = []
for p in prec:
    
    pre = p[0]
    suc = p[1]
    
    vars = []
    a = []
    for q in range(qb_amount):
        vars.append(L_q(L(pre), q))
        a.append(2**q)
    for q in range(qb_amount):
        vars.append(L_q(L(suc), q))
        a.append(-2**q)
    for q in range(qb_amount):
        vars.append(slack("1", pre, q))
        a.append(-2**q)

    Q_C1.extend(linear_constraint(x, vars, a))

# print(Q_C1)
P_C1 = 2000
update_Q(Q, Q_C1, P_C1)
# print_Q_nonZero(Q, x)


##### 4.1.1.1) Precedent constraints on variables bz (optional)
  
    bz_i' = 1 if bz_i = 1 for all precedent operations i' -> i

  Penalty: bz_i *(1 - bz_i')
  
    bz_(JB1,B1,M2,1) * (1 - bz_(JB1,LAM1,M1,1) )
    bz_(JB1,B1,M2,1) * (1 - bz_(JB1,LAM2,M1,1) )
    bz_(JB1,B1,M3,1) * (1 - bz_(JB1,LAM1,M1,2) )
    bz_(JB1,B1,M3,1) * (1 - bz_(JB1,LAM2,M1,2) )
    bz_(JB2,B2,M2,1) * (1 - bz_(JB2,LAM1,M1,1) )

In [1907]:
# Q = np.zeros((len(x), len(x)))
# P(bz - bz*bz')
Q_C1_1 = []
for p in prec:
    
    bz_pre = bz(L(p[0]))
    bz_suc = bz(L(p[1]))
    
    add_Q_value(x, Q_C1_1, bz_suc, bz_suc, 1)
    add_Q_value(x, Q_C1_1, bz_suc, bz_pre, -1/2)


P_C1_1 = 2000
update_Q(Q, Q_C1_1, P_C1_1)
# print_Q_nonZero(Q, x)

#### 4.1.2) Total amount of job

  $$ \sum_{ms} {L_{j(p_j)ms}} \geq a_j $$
    
  (*) p_j = final product of job j

    a_j = sum_ms {L_j(p_j)ms}
    a_JB1 = L_(JB1,B1,M2,1) + L_(JB1,B1,M3,1)
    a_JB2 = L_(jB2,B2,M2,1)

In [1908]:
# Q = np.zeros((len(x), len(x)))
# P(L - a - slack)^2
Q_C1_2 = []
C_C1_2 = 0

for j in J:
    b = j.amount
    vars = []
    a = []
    for of in j.final_operations:
        for q in range(qb_amount):
            vars.append(L_q(L(of), q))
            a.append(2**q)
        for q in range(qb_amount):
            vars.append(slack("1_2", of, q))
            a.append(-2**q)
    
    Q_C1_2.extend(linear_constraint(x, vars, a, b))
    C_C1_2 += b**2

P_C1_2 = P_C1
# print(Q_C1_2)
update_Q(Q, Q_C1_2, P_C1_2)
C += P_C1_2 * C_C1_2
print(C_C1_2)
# print_Q_nonZero(Q, x)


20



### 4.2) Definition of bz

$$ bz_{jpms} = 1\times(L_{jpms} = 0) $$

    bz := (L <= 0)
    (L + Mbz - 1 - slack)^2
    M >= {L_max; 1 - L_min}
         -> M = 16
    slack_max = M - 1 = 15 (4qb)

$$ P {(L_{jpms} + M \times bz_{jpms} - 1 - slack)} ^2 $$

In [1909]:
# (L + M*bz - 1 - slack)^2
M0 = 16
Q_C2 = []
C_C2 = 0

b = 1

for bz_var in bz_list:

    vars = []
    a = []
    
    for q in range(qb_amount):
        vars.append(L_q(bz_var.l, q))
        a.append(2**q)
    
    vars.append(bz_var)
    a.append(M0)

    for q in range(qb_amount):
        vars.append(slack("2", bz_var.l, q))
        a.append(-2**q)
    
    Q_C2.extend(linear_constraint(x, vars, a, b))
    C_C2 += b**2

# print(Q_C2)
# print(len(Q_C2))
# for q in Q_C2:
#     print(x[q[0]], x[q[1]], q[2])
P_C2 = P_C1
update_Q(Q, Q_C2, P_C2)
C += P_C2 * C_C2
print(C_C2)
# print_Q_nonZero(Q,x)



8


In [1910]:
# Q_coef = 1
# sampleset = sendToDwave(Q_coef * Q, 150, beta_range=(0.01, 7))
# samples_dict = count_elements(sampleset, len(Q))
# make_histogram(samples_dict)

# for i in x:
#     print(f"{i} = {lowest_energy(sampleset)[0][x.index(i)]}")



In [1911]:
# print(lowest_energy(sampleset)[1])
# print_all_variables(lowest_energy(sampleset)[0], x, S_q, L_q, E_q, slack, qb_amount)

  
### 4.3) Definition of d_j

$$ d_j = 1 \times ( E_j \leq D_j ) $$

(delta_j^max not considered)

    E_j - D_j >= 1 - M*d_j
    -> (E_j - D_j + M*d_j - 1 - slack)^2
  con slack <= M - 1      \\\\ con M = 16, alcanza un slack de 4 qb (slack maximo = 15)


In [1912]:
# (E_j - D_j + M*d_j - 1 - slack)^2

M0 = 16
Q_C3 = []
C_C3 = 0

for e in E_list:
    j = e.job

    b = 1 + j.deadline
    vars = []
    a = []
    
    for q in range(qb_amount):
        vars.append(E_q(e, q))
        a.append(2**q)
    
    vars.append(d(j))
    a.append(M0)

    for q in range(qb_amount):
        vars.append(slack("3", e, q))
        a.append(-2**q)
    
    Q_C3.extend(linear_constraint(x, vars, a, b))
    C_C3 += b**2

P_C3 = 2000
update_Q(Q, Q_C3, P_C3)
C += P_C3 * C_C3
print(C_C3)



265



### 4.4) Definition of ntz_m

    ntz_m = sum_jps( bz_jpms )  (((((( not necessary ))))))



<h3>4.5) Definition of X^m matrices.</h3>
Null row for each null operation

    sum_k ( X^m_(jps,k) ) = 1 - bz_jpms


In [1913]:
# (sum_k ( X^m_(jps,k) ) + bz_jpms - 1)^2
# Q = np.zeros((len(x), len(x)))

Q_C5 = []
C_C5 = 0

for o in O:

    b = 1
    vars = []
    a = []
    
    for k in range(len(OM[M.index(o.machine)])):
        vars.append(X(o, k+1))
        a.append(1)

    vars.append(bz(L(o)))
    a.append(1)
    
    Q_C5.extend(linear_constraint(x, vars, a, b))
    C_C5 += b**2

P_C5 = 2000
# print(Q_C5)
update_Q(Q, Q_C5, P_C5)
C += P_C5 * C_C5
print(C_C5)
# print_Q_nonZero(Q,x)


8



### 4.6) Definition of u_mk

$$ u_{mk} = 1\times( k <= o_m - \sum_{jps} {bz_{jpms}} ) $$

    for all m and k
    
      k <= o_m - sum(bz)
      -> (k - o_m + sum(bz) + M * u_mk - 1 - slack)^2
      -> slack_max = M - 1
      -> M >= max{ k , 1 - k + o_m }

In [1914]:
Q_C6 = []
C_C6 = 0

# for all m and k    
# (k - o_m + sum(bz) + M * u_mk - 1 - slack)^2
# slack_max = M - 1
# M >= max{ k , 1 - k + o_m }
# b = o_m - k + 1
# slack de n qubits:
#   M = 2^n
#   n = techo{ log2(max{k,1-k+o_m}) } = techo{ log2(max{k,b}) }

for u_mk in u_list:

    m = u_mk.machine
    k = u_mk.k

    m_op_list = OM[M.index(m)]
    
    b = len(m_op_list) - k + 1
    vars = []
    a = []

    n = math.ceil(math.log2(max(k, b)))
    M_u = 2**n

    for o in m_op_list:
        vars.append(bz(L(o)))
        a.append(1)

    for q in range(n):
        vars.append(slack("6", u_mk, q))
        a.append(-2**q)

    vars.append(u_mk)
    a.append(M_u)

    Q_C6.extend(linear_constraint(x, vars, a, b))
    C_C6 += b**2
    

P_C6 = P_C5
# print(Q_C6)
update_Q(Q, Q_C6, P_C6)
C += P_C6 * C_C6
print(C_C6)
# print_Q_nonZero(Q,x)
      


61



#### 4.6.1) X columns with only one "1" or none
  $$ \sum_{jps} { X^m_{jps,k} } = u_{mk} $$
    for all m and k


In [1915]:
Q_C6_1 = []

# ( sum_jps {X^m_(jps,k)} - u_mk )^2

for u_mk in u_list:

    m = u_mk.machine
    k = u_mk.k

    m_op_list = OM[M.index(m)]
        
    vars = []
    a = []

    for o in m_op_list:
        vars.append(X(o,k))
        a.append(1)
        
    vars.append(u_mk)
    a.append(-1)

    Q_C6_1.extend(linear_constraint(x, vars, a))

P_C6_1 = P_C6
# print(Q_C6_1)
update_Q(Q, Q_C6_1, P_C6_1)
# print_Q_nonZero(Q,x)

In [1916]:
# gp_model = gp.Model()
# xv = np.array([[gp_model.addVar(vtype = gp.GRB.BINARY, name = f'x{i}') for i in range(len(x))]])
# obj = (xv*np.matrix(Q)*np.transpose(xv))[0,0]
# gp_model.params.NonConvex = -1
# gp_model.setParam("TimeLimit", 120)
# gp_model.setObjective(obj, gp.GRB.MINIMIZE)
# gp_model.optimize()
# result = np.array([var.x for var in gp_model.getVars()])

In [1917]:
# print((result@np.matrix(Q)@np.transpose(result))[0,0])
# print_all_variables(result, x, S_q, L_q, E_q, slack, X, qb_amount)


In [1918]:
# result_2 = [[x[gp_model.getVars().index(var)], var.x] for var in gp_model.getVars()]
# i = 0
# for v in result_2:
#     x_var = x[result_2.index(v)]
#     print(x_var)
#     if x_var == u(M[1], 1):
#         v = 1
#         i = result_2.index(v)

# print(i)
# print(result_2[i])

# print((result_2@np.matrix(Q)@np.transpose(result_2))[0,0])
# print_all_variables(result, x, S_q, L_q, E_q, slack, X, qb_amount)



### 4.7) Precedence restriction

#### 4.7.1) By precedence

$$ S_{jp'm's'} \geq S_{jpms} + L_{jpms} $$
    for all precedences pms -> p'm's'

    (S_jp'm's' - S_jpms - L_jpms - slack)^2


In [1919]:

Q_C7_1 = []
for p in prec:
    
    pre = p[0]
    suc = p[1]
    
    vars = []
    a = []
    for q in range(qb_amount):
        vars.append(S_q(S(suc), q))
        a.append(2**q)
    for q in range(qb_amount):
        vars.append(S_q(S(pre), q))
        a.append(-2**q)
    for q in range(qb_amount):
        vars.append(L_q(L(pre), q))
        a.append(-2**q)
    for q in range(qb_amount):
        vars.append(slack("7_1", pre, q))
        a.append(-2**q)

    Q_C7_1.extend(linear_constraint(x, vars, a))

# print(Q_C7_1)
P_C7_1 = 2000
update_Q(Q, Q_C7_1, P_C7_1)
# print_Q_nonZero(Q, x)


##### 4.7.1.1) Final dummy operation

$$ E_j \geq S_{jp_{j}ms} + L_{jp_{j}ms} $$

    (E_j - S_j(p_j)ms - L_j(p_j)ms - slack)^2
    (*) p_j is the final product of job j


In [1920]:

Q_C7_1_1 = []

for j in J:
    for of in j.final_operations:
        
        vars = []
        a = []

        for q in range(qb_amount):
            vars.append(E_q(E(j), q))
            a.append(2**q)
        for q in range(qb_amount):
            vars.append(S_q(S(of), q))
            a.append(-2**q)
        for q in range(qb_amount):
            vars.append(L_q(L(of), q))
            a.append(-2**q)
        for q in range(qb_amount):
            vars.append(slack("7_1_1", of, q))
            a.append(-2**q)

        Q_C7_1_1.extend(linear_constraint(x, vars, a))

# print(Q_C7_1_1)
P_C7_1_1 = 2000
update_Q(Q, Q_C7_1_1, P_C7_1_1)
# print_Q_nonZero(Q, x)


#### 4.7.2) Alternatively (+M)

$$ S_{jp'm's'} \geq S_{jpms} + L_{jpms} - M \times bz_{jpms} $$
    
    //for all precedences pms -> p'm's'
    S_jp'm's' = S_jpms + L_jpms - M * bz_jpms + slack
    -> slack_max = max{ S' - S + M } = 15 + M ~ 2*M (5qb)

    S' >= S - M
    M >= max{S-S'} = 15 -> M = 15 o 16



##### 4.7.2.1) Final dummy operation

$$ E_j \geq S_{jp_{j}ms} + L_{jp_{j}ms} - M \times bz_{jp_{j}ms} $$
    for all m, s
    E_j = S_j(p_j)ms + L_j(p_j)ms - M * bz_j(p_j)ms + slack
    -> slack_max = max{ E - S + M } = 15 + M ~ 2*M (5qb)

    M >= S - E iff M >= max{S-E} = 15 -> M = 15 or 16



#### 4.7.3) A possible reinforcing constraint

$$ \sum_{k} {X^{m}_{(jp's'),k} \times k} + M \times bz_{jp'ms'} \geq \sum_{k} {X^m_{(jps)k}\times k} - M\times bz_{jpms} $$


In [1921]:
# result_array = []
# reads = 2

# for i in range(reads):
#     gp_model = gp.Model()
#     xv = np.array([[gp_model.addVar(vtype = gp.GRB.BINARY, name = f'x{i}') for i in range(len(x))]])
#     obj = (xv*np.matrix(Q)*np.transpose(xv))[0,0]
#     gp_model.params.NonConvex = -1
#     gp_model.setParam("TimeLimit", 60)
#     gp_model.setObjective(obj, gp.GRB.MINIMIZE)
#     gp_model.optimize()
#     res = np.array([var.x for var in gp_model.getVars()])
#     result_array.append( [ res, (res@np.matrix(Q)@np.transpose(res))[0,0] ] )
    
# result = lowest_energy(np.array(result_array))[0][0]

In [1922]:
# result = lowest_energy(result_array)[0][0]
# # print((result@np.matrix(Q)@np.transpose(result))[0,0])
# print_all_variables(result_array[1][0], x, S_q, L_q, E_q, slack, X, qb_amount)

In [1923]:
# result_2 = result.copy()
# for v in x:
#     if v == d(J[1]) or (isinstance(v, slack) and v.same(slack('3',E(J[1]),0))):
#         result_2[x.index(v)] = 0
        
# print(len(result_2))
# print((result@np.matrix(Q)@np.transpose(result))[0,0])
# print((result_2@np.matrix(Q)@np.transpose(result_2))[0,0])
# print_all_variables(result_2, x, S_q, L_q, E_q, slack, X, qb_amount)


### 4.8) Nonsuperposition of operations:
for each machine m, k = 2,...o_m

$$ \sum_{jps} {
      S_{jpms} X^m_{jps,k}
    }

    \geq \sum_{jps} {
      ( S_{jpms} + L_{jpms} ) X^m_{jps,k-1}
    }

    + \sum_{jps, j'p's'} {
      X^m_{jps,k-1} TT^m_{p,p'} X^m_{j'p's',k}
    }
    
    - M (1 - u_{mk}) $$




#### 4.8.1) Avoiding the quadratic terms
  
$$  \sum_{jps,q} {
      2^q y^m_{jps,k,q}
    }
    \geq \sum_{jps,q} {
      2^q (y^m_{jps,k-1,q} + z^m_{jps,k-1,q})
    }
    + \sum_{jps, j'p's'} {
      TT^m_{p,p'} w^m_{jps,j'p's',k}
    }
    - M (1 - u_{mk})
$$
for all machine m and column k = 2,3,...,o_m


In [1924]:
# ( sum(y) - sum(y') - sum(z) - sum(TT*w) - M*u - slack + M )^2

Q_C8 = []
C_C8 = 0
M0 = 32

for m in M:
    op_list = OM[M.index(m)]
    for k in range(2, len(op_list) + 1):
        
        vars = []
        a = []
        b = -M0

        for o in op_list:
            for q in range(qb_amount):
                vars.append(AuxQuadXLS(o, k, q, "y"))
                a.append(2**q)

        for o in op_list:           
            for q in range(qb_amount):
                vars.append(AuxQuadXLS(o, k-1, q, "y"))
                a.append(-2**q)

        for o in op_list:               
            for q in range(qb_amount):
                vars.append(AuxQuadXLS(o, k-1, q, "z"))
                a.append(-2**q)

        for o1 in op_list:
            for o2 in op_list:
                if len(op_list)>1 and o1 != o2:
                    vars.append(AuxQuadXs(o1, o2, k))
                    a.append( - TT[M.index(m)] [P.index(o1.product)] [P.index(o2.product)])

        vars.append(u(m, k))
        a.append(-M0)

        for q in range(6):
            vars.append(slack("8", u(m, k), q))
            a.append(-2**q)

        Q_C8.extend(linear_constraint(x, vars, a, b))
        C_C8 += b**2

# print(Q_C8)
P_C8 = 2000

# update_Q(Q, Q_C8, P_C8)
# C += P_C8 * C_C8

print(C_C8)
# print_Q_nonZero(Q, x)

5120



### 4.9) Quadratic constraint auxiliary variables



#### 4.9.1) X and S

$$ y^m_{jps,k,q} = X^m_{jps,k} * {S_{jpms}}_q $$
$$ P \times ( 3 \times y^m_{jps,k,q} + X^m_{jps,k} \times {S_{jpms}}_q - 2 \times {S_{jpms}}_q \times y^m_{jps,k,q} - 2 \times X^m_{jps,k} \times y^m_{jps,k,q} ) $$


In [1925]:
# P(3*y + X*S - 2*S*y - 2*X*y)

Q_C9_1 = []

for y in y_list:

    o = y.operation
    k = y.k
    q = y.qbit

    add_Q_value(x, Q_C9_1, y, y, 3)
    add_Q_value(x, Q_C9_1, X(o,k), S_q(S(o),q), 1/2)
    add_Q_value(x, Q_C9_1, S_q(S(o),q), y, -1)
    add_Q_value(x, Q_C9_1, X(o,k), y, -1)

P_C9_1 = 2000
# update_Q(Q, Q_C9_1, P_C9_1)
# print_Q_nonZero(Q, x)


#### 4.9.2) X and L
$$ z^m_{jps,k,q} = X^m_{jps,k} * {L_{jpms}}_q $$
$$ P \times ( 3 \times z^m_{jps,k,q} + X^m_{jps,k} \times {L_{jpms}}_q - 2 \times {L_{jpms}}_q \times z^m_{jps,k,q} - 2 \times X^m_{jps,k} \times z^m_{jps,k,q} ) $$


In [1926]:
# P(3*z + X*L - 2*L*z - 2*X*z)

Q_C9_2 = []

for z in z_list:

    o = z.operation
    k = z.k
    q = z.qbit

    add_Q_value(x, Q_C9_2, z, z, 3)
    add_Q_value(x, Q_C9_2, X(o,k), L_q(L(o),q), 1/2)
    add_Q_value(x, Q_C9_2, L_q(L(o),q), z, -1)
    add_Q_value(x, Q_C9_2, X(o,k), z, -1)

# print(len(Q_C9_2))
P_C9_2 = 2000
# update_Q(Q, Q_C9_2, P_C9_2)
# print_Q_nonZero(Q, x)


#### 4.9.3) X and X
$$ w^m_{(jps),(j'p's'),k} = X^m_{jps,k-1} * X^m_{j'p's',k} $$
$$ P \times ( 3 \times w^m_{(jps),(j'p's'),k} + X^m_{jps,k-1} \times X^m_{j'p's',k} - 2 \times X^m_{j'p's',k} \times w^m_{(jps),(j'p's'),k} - 2 \times X^m_{jps,k-1} \times w^m_{(jps),(j'p's'),k} ) $$


In [1927]:
# P(3*w + X*X' - 2*X'*w - 2*X*w)

# Q = np.zeros((len(x), len(x)))

Q_C9_3 = []

for w in w_list:

    o1 = w.operation1
    o2 = w.operation2
    k = w.k

    add_Q_value(x, Q_C9_3, w, w, 3)
    add_Q_value(x, Q_C9_3, X(o1,k-1), X(o2,k), 1/2)
    add_Q_value(x, Q_C9_3, X(o2,k), w, -1)
    add_Q_value(x, Q_C9_3, X(o1,k-1), w, -1)

# print(Q_C9_3)
P_C9_3 = 2000
# update_Q(Q, Q_C9_3, P_C9_3)
# print_Q_nonZero(Q, x)

In [1928]:
Q_C = Q.copy() - Q_FO.copy()
C_C = C - C_FO
print(C_C)
print(C_FO)

724000
8500


In [1929]:
print(C) #final constant

732500


## Solvers 

### Gurobi

In [184]:
result_array = []
reads = 1

for i in range(reads):
    gp_model = gp.Model()
    xv = np.array([[gp_model.addVar(vtype = gp.GRB.BINARY, name = f'x{i}') for i in range(len(x))]])
    obj = (xv*np.matrix(Q)*np.transpose(xv))[0,0]
    gp_model.params.NonConvex = -1
    gp_model.setParam("TimeLimit", 60*60*4)
    gp_model.setObjective(obj, gp.GRB.MINIMIZE)
    gp_model.optimize()
    res = np.array([var.x for var in gp_model.getVars()])
    result_array.append( [ res, (res@np.matrix(Q)@np.transpose(res))[0,0] ] )
    
# result = lowest_energy(np.array(result_array))[0][0]

Set parameter TimeLimit to value 14400
Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 0 rows, 206 columns and 0 nonzeros
Model fingerprint: 0x15854837
Model has 1837 quadratic objective terms
Variable types: 0 continuous, 206 integer (206 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  QObjective range [2e+02, 1e+06]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Found heuristic solution: objective 0.0000000
Found heuristic solution: objective -669050.0000
Found heuristic solution: objective -675100.0000
Presolve removed 0 rows and 2 columns
Presolve time: 0.02s
Presolved: 0 rows, 204 columns, 0 nonzeros
Presolved model has 1863 quadratic objective terms
Variable types: 0 continuous, 204 integer (204 binary)

Root rela

  3041  2192 -1763323.0   31  953 -718250.00 -1763323.0   146%  96.9   15s
  4632  3084 -1763323.0   53  615 -718250.00 -1763323.0   146%  98.7   20s
  6449  4382 -1763323.0   30  952 -718250.00 -1763323.0   146%  99.3   25s
  8913  6581 -1763323.0   37  811 -718250.00 -1763323.0   146%   100   30s
 11144  8456 -1763323.0   33  902 -718250.00 -1763323.0   146%   101   35s
 13474 10184 -1227375.0   69  479 -718250.00 -1763323.0   146%   101   41s
H13618 10183                    -718450.0000 -1763323.0   145%   101   41s
H13631 10183                    -719050.0000 -1763323.0   145%   101   41s
 15479 11881 -1066969.9   68  539 -719050.00 -1763323.0   145%   101   46s
 17482 13605 -1496540.4   44  703 -719050.00 -1763323.0   145%   101   50s
 20119 15168 -1763323.0   42  771 -719050.00 -1763323.0   145%   100   55s
 22271 16752 -1763323.0   34  899 -719050.00 -1763323.0   145%   102   61s
 23913 18371 -1739835.6   35  748 -719050.00 -1763323.0   145%   102   65s
 27494 20681 -1763323.0  

In [188]:
# result = result_array[0][0]
# r = (result@np.matrix(Q)@np.transpose(result))[0,0]
# print(r)
# print(r + C)
# print_all_variables(result_array[0][0], x, S_q, L_q, E_q, slack, X, qb_amount)

-721700.0
206
S{JB1,LAM1,M1,1} = 0.0
S{JB1,LAM1,M1,2} = 2.0
S{JB1,LAM2,M1,1} = 0.0
S{JB1,LAM2,M1,2} = 5.0
S{JB1,B1,M2} = 2.0
S{JB1,B1,M3} = 8.0
S{JB2,LAM1,M1} = 0.0
S{JB2,B2,M2} = 2.0
L{JB1,LAM1,M1,1} = 2.0
L{JB1,LAM1,M1,2} = 2.0
L{JB1,LAM2,M1,1} = 2.0
L{JB1,LAM2,M1,2} = 2.0
L{JB1,B1,M2} = 2.0
L{JB1,B1,M3} = 2.0
L{JB2,LAM1,M1} = 2.0
L{JB2,B2,M2} = 2.0
E{JB1} = 10.0
E{JB2} = 5.0
d{JB1} = 1.0
d{JB2} = 1.0
bz{L{JB1,LAM1,M1,1}} = 0.0
bz{L{JB1,LAM1,M1,2}} = 0.0
bz{L{JB1,LAM2,M1,1}} = 0.0
bz{L{JB1,LAM2,M1,2}} = 0.0
bz{L{JB1,B1,M2}} = 0.0
bz{L{JB1,B1,M3}} = 0.0
bz{L{JB2,LAM1,M1}} = 0.0
bz{L{JB2,B2,M2}} = 0.0
X^M1 =
[[0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]]
X^M2 =
[[0 1]
 [1 0]]
X^M3 =
[[1]]
u_{M1,1} = 1.0
u_{M1,2} = 1.0
u_{M1,3} = 1.0
u_{M1,4} = 1.0
u_{M1,5} = 1.0
u_{M2,1} = 1.0
u_{M2,2} = 1.0
u_{M3,1} = 1.0
slack_2_L{JB1,LAM1,M1,1} = 1.0
slack_2_L{JB1,LAM1,M1,2} = 1.0
slack_2_L{JB1,LAM2,M1,1} = 1.0
slack_2_L{JB1,LAM2,M1,2} = 1.0
slack_2_L{JB1,B1,M2} = 1.0
slack_2_L{JB

In [192]:
# gp_model.setParam("TimeLimit", 30)
# gp_model.optimize()


Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 0 rows, 206 columns and 0 nonzeros
Model fingerprint: 0x15854837
Model has 1837 quadratic objective terms
Variable types: 0 continuous, 206 integer (206 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  QObjective range [2e+02, 1e+06]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Presolved: 0 rows, 204 columns, 0 nonzeros
Presolved model has 1863 quadratic objective terms

Continuing optimization...

 4209457 2786760 -1068309.6   56  772 -721700.02 -1134675.4  57.2%  89.2 49835s
 4210846 2787962 -1016227.2   57  679 -721700.02 -1134640.0  57.2%  89.2 49841s
 4212644 2789059 -729834.95   89  266 -721700.02 -1134606.9  57.2%  89.2 49847s
 4214334 2789801 -958847.15   57  701 

KeyboardInterrupt: 

Exception ignored in: 'gurobipy.logcallbackstub'
Traceback (most recent call last):
  File "c:\Users\marzu\OneDrive - Universidad de Montevideo\Documentos\MARCO\um\Nueva carpeta\dwave\JSSP\.venv\lib\site-packages\ipykernel\iostream.py", line 610, in write
    def write(self, string: str) -> Optional[int]:  # type:ignore[override]
KeyboardInterrupt: 


 4619972 3054523 -967233.34   57  715 -721700.02 -1128045.5  56.3%  88.3 62365s
 4621257 3055333 -879697.10   60  702 -721700.02 -1128026.8  56.3%  88.3 62371s


KeyboardInterrupt: 

Exception ignored in: 'gurobipy.logcallbackstub'
Traceback (most recent call last):
  File "c:\Users\marzu\OneDrive - Universidad de Montevideo\Documentos\MARCO\um\Nueva carpeta\dwave\JSSP\.venv\lib\site-packages\ipykernel\iostream.py", line 610, in write
    def write(self, string: str) -> Optional[int]:  # type:ignore[override]
KeyboardInterrupt: 


 4624234 3057588 -1046512.6   53  789 -721700.02 -1127985.5  56.3%  88.3 62387s
 4626122 3058490 -1046640.1   62  800 -721700.02 -1127955.5  56.3%  88.3 62399s
 4627514 3059347 -754493.63   73  524 -721700.02 -1127937.9  56.3%  88.3 62405s
 4628867 3060443 -1027365.1   57  673 -721700.02 -1127915.3  56.3%  88.3 62411s
 4630432 3061340 -1045348.7   63  771 -721700.02 -1127894.5  56.3%  88.3 62417s
 4631829 3062170 -940943.58   63  707 -721700.02 -1127873.2  56.3%  88.3 62423s
 4633185 3063122 -1002328.4   57  736 -721700.02 -1127849.1  56.3%  88.3 62430s
 4634601 3064066 -723645.27   87  324 -721700.02 -1127827.8  56.3%  88.3 62440s
 4636013 3064968 -866414.58   62  563 -721700.02 -1127802.0  56.3%  88.3 62447s
 4637604 3065980 -1008471.4   60  770 -721700.02 -1127773.3  56.3%  88.3 62458s
 4639198 3066954 -991654.15   55  840 -721700.02 -1127745.2  56.3%  88.3 62465s
 4640640 3068126 -1026073.9   50  763 -721700.02 -1127723.5  56.3%  88.3 62470s
 4642342 3069286 -998484.21   54  794 -7

In [381]:
# gp_model.setParam("TimeLimit", 30)
# gp_model.optimize()
# res = np.array([var.x for var in gp_model.getVars()])
# result_array.append( [ res, (res@np.matrix(Q)@np.transpose(res))[0,0] ] )
result = result_array[1][0]
r = (result@np.matrix(Q)@np.transpose(result))[0,0]
print(r)
print(r + C)
print_all_variables(result_array[0][0], x, S_q, L_q, E_q, slack, X, qb_amount)

-721700.0
10800.0
206
S{JB1,LAM1,M1,1} = 0.0
S{JB1,LAM1,M1,2} = 2.0
S{JB1,LAM2,M1,1} = 0.0
S{JB1,LAM2,M1,2} = 5.0
S{JB1,B1,M2} = 2.0
S{JB1,B1,M3} = 8.0
S{JB2,LAM1,M1} = 0.0
S{JB2,B2,M2} = 2.0
L{JB1,LAM1,M1,1} = 2.0
L{JB1,LAM1,M1,2} = 2.0
L{JB1,LAM2,M1,1} = 2.0
L{JB1,LAM2,M1,2} = 2.0
L{JB1,B1,M2} = 2.0
L{JB1,B1,M3} = 2.0
L{JB2,LAM1,M1} = 2.0
L{JB2,B2,M2} = 2.0
E{JB1} = 10.0
E{JB2} = 5.0
d{JB1} = 1.0
d{JB2} = 1.0
bz{L{JB1,LAM1,M1,1}} = 0.0
bz{L{JB1,LAM1,M1,2}} = 0.0
bz{L{JB1,LAM2,M1,1}} = 0.0
bz{L{JB1,LAM2,M1,2}} = 0.0
bz{L{JB1,B1,M2}} = 0.0
bz{L{JB1,B1,M3}} = 0.0
bz{L{JB2,LAM1,M1}} = 0.0
bz{L{JB2,B2,M2}} = 0.0
X^M1 =
[[0 0 0 1 0]
 [0 0 1 0 0]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 1]]
X^M2 =
[[0 1]
 [1 0]]
X^M3 =
[[1]]
u_{M1,1} = 1.0
u_{M1,2} = 1.0
u_{M1,3} = 1.0
u_{M1,4} = 1.0
u_{M1,5} = 1.0
u_{M2,1} = 1.0
u_{M2,2} = 1.0
u_{M3,1} = 1.0
slack_2_L{JB1,LAM1,M1,1} = 1.0
slack_2_L{JB1,LAM1,M1,2} = 1.0
slack_2_L{JB1,LAM2,M1,1} = 1.0
slack_2_L{JB1,LAM2,M1,2} = 1.0
slack_2_L{JB1,B1,M2} = 1.0
slac

In [1936]:
gp_model = gp.Model()
xv = np.array([[gp_model.addVar(vtype = gp.GRB.BINARY, name = f'x{i}') for i in range(len(x))]])
obj = (xv*np.matrix(Q)*np.transpose(xv))[0,0]
gp_model.params.NonConvex = -1
gp_model.setParam("TimeLimit", 60*10)
gp_model.setObjective(obj, gp.GRB.MINIMIZE)
gp_model.optimize()
result = np.array([var.x for var in gp_model.getVars()])

Set parameter TimeLimit to value 600
Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 0 rows, 238 columns and 0 nonzeros
Model fingerprint: 0x141353e0
Model has 2178 quadratic objective terms
Variable types: 0 continuous, 238 integer (238 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  QObjective range [2e+02, 1e+06]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]

Loaded MIP start from previous solve with objective -720700



Presolve removed 0 rows and 2 columns
Presolve time: 0.03s
Presolved: 0 rows, 236 columns, 0 nonzeros
Presolved model has 2204 quadratic objective terms
Variable types: 0 continuous, 236 integer (236 binary)

Root relaxation: objective -1.957492e+06, 202 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objective Bounds      |     Work
 Expl Unexpl |  Obj  Depth IntInf | Incumbent    BestBd   Gap | It/Node Time

     0     0 -1957491.9    0  142 -720700.00 -1957491.9   172%     -    0s
     0     0 -1957491.9    0  142 -720700.00 -1957491.9   172%     -    0s
     0     2 -1957491.9    0  142 -720700.00 -1957491.9   172%     -    0s
  1434  1232 -987720.56   31 1492 -720700.00 -1502635.8   108%   4.8    5s
  1447  1241 -824598.45   65 1573 -720700.00 -1502635.8   108%   4.7   10s
  1459  1249 -959162.97   33 1600 -720700.00 -1502635.8   108%   4.7   15s
  1477  1261 -872850.35   50 1572 -720700.00 -1502635.8   108%   4.6   20s
  1516  1300 -1502635.8 

In [1937]:
result = np.array([var.x for var in gp_model.getVars()])
r = (result@np.matrix(Q)@np.transpose(result))[0,0]
print(r)
print(r + C)
print_all_variables(result, x, S_q, L_q, E_q, slack, X, qb_amount)

-720800.0
11700.0
238
S{JB1,LAM1,M1,1} = 1.0
S{JB1,LAM1,M1,2} = 1.0
S{JB1,LAM2,M1,1} = 2.0
S{JB1,LAM2,M1,2} = 2.0
S{JB1,B1,M2} = 5.0
S{JB1,B1,M3} = 8.0
S{JB2,LAM1,M1} = 0.0
S{JB2,B2,M2} = 7.0
L{JB1,LAM1,M1,1} = 2.0
L{JB1,LAM1,M1,2} = 4.0
L{JB1,LAM2,M1,1} = 1.0
L{JB1,LAM2,M1,2} = 4.0
L{JB1,B1,M2} = 1.0
L{JB1,B1,M3} = 4.0
L{JB2,LAM1,M1} = 2.0
L{JB2,B2,M2} = 2.0
E{JB1} = 12.0
E{JB2} = 11.0
d{JB1} = 0.0
d{JB2} = 1.0
bz{L{JB1,LAM1,M1,1}} = 0.0
bz{L{JB1,LAM1,M1,2}} = 0.0
bz{L{JB1,LAM2,M1,1}} = 0.0
bz{L{JB1,LAM2,M1,2}} = 0.0
bz{L{JB1,B1,M2}} = 0.0
bz{L{JB1,B1,M3}} = 0.0
bz{L{JB2,LAM1,M1}} = 0.0
bz{L{JB2,B2,M2}} = 0.0
X^M1 =
[[0 0 0 1 0]
 [0 0 0 0 1]
 [0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 1 0 0]]
X^M2 =
[[1 0]
 [0 1]]
X^M3 =
[[1]]
u_{M1,1} = 1.0
u_{M1,2} = 1.0
u_{M1,3} = 1.0
u_{M1,4} = 1.0
u_{M1,5} = 1.0
u_{M2,1} = 1.0
u_{M2,2} = 1.0
u_{M3,1} = 1.0
slack_1_JB1,LAM1,M1,1 = 1.0
slack_1_JB1,LAM2,M1,1 = 0.0
slack_1_JB1,LAM1,M1,2 = 0.0
slack_1_JB1,LAM2,M1,2 = 0.0
slack_1_JB2,LAM1,M1 = 0.0
slack_1_2_JB1,B1

In [1938]:
r_c = (result@np.matrix(Q_C)@np.transpose(result))[0,0]
print(r_c)
print(r_c + C_C)

-724000.0
0.0


In [659]:
# gp_model = gp.Model()
# xv = np.array([[gp_model.addVar(vtype = gp.GRB.BINARY, name = f'x{i}') for i in range(len(x))]])
# obj = (xv*np.matrix(Q)*np.transpose(xv))[0,0]
# gp_model.params.NonConvex = -1
# gp_model.setParam("TimeLimit", 60)
# gp_model.setObjective(obj, gp.GRB.MINIMIZE)
gp_model.optimize()
result = np.array([var.x for var in gp_model.getVars()])

Gurobi Optimizer version 10.0.2 build v10.0.2rc0 (win64)

CPU model: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz, instruction set [SSE2|AVX|AVX2]
Thread count: 6 physical cores, 12 logical processors, using up to 12 threads

Optimize a model with 0 rows, 206 columns and 0 nonzeros
Model fingerprint: 0xaa33e53d
Model has 1468 quadratic objective terms
Variable types: 0 continuous, 206 integer (206 binary)
Coefficient statistics:
  Matrix range     [0e+00, 0e+00]
  Objective range  [0e+00, 0e+00]
  QObjective range [4e+03, 1e+06]
  Bounds range     [1e+00, 1e+00]
  RHS range        [0e+00, 0e+00]
Presolved: 0 rows, 192 columns, 0 nonzeros
Presolved model has 1495 quadratic objective terms

Continuing optimization...

 29814 23200 -1190948.5   39  723 -722000.00 -1803618.7   150%  79.2   61s
 33085 26646 -1562335.2   43  642 -722000.00 -1775983.5   146%  79.4   65s
 36083 27778 -1072639.1   56  186 -722000.00 -1764569.1   144%  79.1   79s
 36085 27779 -998744.38   55  153 -722000.00 -1764569

In [950]:
print(C)

724000


In [658]:
r = (result@np.matrix(Q)@np.transpose(result))[0,0]
print(r)
print(r + C)

print_all_variables(result, x, S_q, L_q, E_q, slack, X, qb_amount)

-722000.0
2000.0
206
S{JB1,LAM1,M1,1} = 1.0
S{JB1,LAM1,M1,2} = 1.0
S{JB1,LAM2,M1,1} = 5.0
S{JB1,LAM2,M1,2} = 6.0
S{JB1,B1,M2} = 10.0
S{JB1,B1,M3} = 9.0
S{JB2,LAM1,M1} = 2.0
S{JB2,B2,M2} = 11.0
L{JB1,LAM1,M1,1} = 3.0
L{JB1,LAM1,M1,2} = 0.0
L{JB1,LAM2,M1,1} = 3.0
L{JB1,LAM2,M1,2} = 0.0
L{JB1,B1,M2} = 3.0
L{JB1,B1,M3} = 0.0
L{JB2,LAM1,M1} = 2.0
L{JB2,B2,M2} = 2.0
E{JB1} = 9.0
E{JB2} = 15.0
d{JB1} = 1.0
d{JB2} = 0.0
bz{L{JB1,LAM1,M1,1}} = -0.0
bz{L{JB1,LAM1,M1,2}} = 1.0
bz{L{JB1,LAM2,M1,1}} = -0.0
bz{L{JB1,LAM2,M1,2}} = 1.0
bz{L{JB1,B1,M2}} = 0.0
bz{L{JB1,B1,M3}} = 1.0
bz{L{JB2,LAM1,M1}} = -0.0
bz{L{JB2,B2,M2}} = 0.0
X^M1 =
[[0 1 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]]
X^M2 =
[[0 1]
 [1 0]]
X^M3 =
[[0]]
u_{M1,1} = 1.0
u_{M1,2} = 1.0
u_{M1,3} = 1.0
u_{M1,4} = 0.0
u_{M1,5} = 0.0
u_{M2,1} = 1.0
u_{M2,2} = 1.0
u_{M3,1} = 0.0
slack_2_L{JB1,LAM1,M1,1} = 2.0
slack_2_L{JB1,LAM1,M1,2} = 15.0
slack_2_L{JB1,LAM2,M1,1} = 2.0
slack_2_L{JB1,LAM2,M1,2} = 15.0
slack_2_L{JB1,B1,M2} = 2.

### Simulated Annealing

In [186]:

# sampleset = sendToDwave(Q, 10)
# print(sampleset)
# samples_dict = count_elements(sampleset, len(Q))
# make_histogram(samples_dict)



### D-Wave

In [187]:
# sampleset = sendToDwaveSampler(Q, 100)
# samples_dict = count_elements(sampleset.record, len(Q))
# make_histogram(samples_dict)

# result = np.array(lowest_energy(sampleset.record)[0])
# print((result@np.matrix(Q)@np.transpose(result))[0,0])
# print_all_variables(result, x, S_q, L_q, E_q, slack, X, qb_amount)

# for i in x:
#     print(f"{i} = {lowest_energy(sampleset.record)[0][x.index(i)]}")